# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: group-goby Action

on:
  push:
    paths:
      - 'app/**'

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [12.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@preview
        with:
          path: ./app/node_modules
          key: ${{ matrix.os }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ matrix.os }}-build-
      
      - name: Install Dependencies
        working-directory: ./app
        run: yarn
      - name: Lint
        working-directory: ./app
        run: yarn lint
      - name: Build
        working-directory: ./app
        run: yarn build
        env:
          FIREBASE_APIKEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTHDOMAIN: ${{ secrets.FIREBASE_AUTHDOMAIN }}
          FIREBASE_DATABASEURL: ${{ secrets.FIREBASE_DATABASEURL }}
          FIREBASE_PROJECTID: ${{ secrets.FIREBASE_PROJECTID }}
